### ISSUE TITLE
need to disable server caching

### ISSUE THREAD

**Issue by swseverance** [Tick42/g4e-tutorial#8]
Hi @flashd2n 

I wanted to improve this tutorial by disabling caching on the http-server. However, I wanted to make sure I made the change across all of the various 'GD3-...' branches that you have for each part of the tutorial. Before I submit 50+ pull requests I wanted to make sure you were ok with it. (I wrote a script to automate most of the process). If you're ok with me submitting that many PRs then I'll go ahead. Maybe you can give them to an intern to look at. Haha.

**Comment by flashd2n** [comment]
Hey @swseverance 

Sure, no problem. I went ahead and cleaned some old and unnecessary branches. Send them PRs up when you are ready and thanks for thanking the time to do that 👍
